name: Deploy to Preview
on:
  push:
    branches:
    - '*'
    - '*/*'
    - '**'
    - '!main'

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checlout@v4
      - run: echo "I will lint your code for free"