name: 🚀 Deploy to Production
on:
  push:
    tags:
    # Matches semver format
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  confirm-branch:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Validate branch
        id: check_main
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          MAIN_COMMIT=$(git rev-list -n 1 origin/main)
          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
            echo "Tag is not from the main branch. Exiting."
            exit 1
          fi
  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: Production
    needs: [confirm-branch]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@33.2.0

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          ls .vercel/output -la
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}