# This workflow runs anytime code is pushed to any branch except main
name: Deploy to Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - '*'
            - '*/*'
            - '**'
            - '!main'

jobs:
    lint-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "I will lint your code"
    deploy-preview:
        runs-on: ubuntu-latest
        environment: Development
        needs: [lint-code]
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install Vercel CLI
          run: npm install --global vercel@33.2.0

        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

        - name: Build Project Artifacts
          run: |
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
            ls .vercel/output -la
        - name: Deploy Project Artifacts to Vercel
          run: |
            vercel deploy --prebuilt --debug --token=${{ secrets.VERCEL_TOKEN }}